version: '3.0'

services:
  web:
    build: .
    ports:
      - ${RAILS_PORT-3000}:3000
    env_file: ".env.production"
    volumes:
      - .:/rails
    depends_on:
      - db
      - sidekiq
    links:
      - db:db
  db:
    image: postgres:15
    env_file: ".env.production"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    ports: 
      - "6379:6379"

  sidekiq:  
    build: .  
    command: bundle exec sidekiq
    env_file: ".env.production"
    volumes:  
      - .:/rails  
    depends_on:  
      - redis

volumes:
  db_data:
