# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  timeout: 5000

development:
  <<: *default
  database: go_market_development

test:
  <<: *default
  database: go_market_test

production:
  <<: *default
  database: go_market_production

# # For production is recommended to set DATABASE_URL env variable.
# # It will take precedence over the config defined here.
# # https://edgeguides.rubyonrails.org/configuring.html#connection-preference
# production:
#   <<: *default
